.TH daytime "1" "Aug 2016" "DAYTIME 2.0" "time client/server supporing SNTP, daytime, time and HTTP." 


.SH SYNPOSIS
.P
	daytime  -daytime|-time|-nist|-http|-sntp <server> [-s] [-r] [-tz <timezone>] [-P <path>] 
	daytime  -sntp-bcast <broadcast net> [-sntp-version <version>]

.SH DESCRIPTION
.P
A trivial program that gets time from daytime, nist daytime, time, SNTP or http servers, and optionally updates the system and/or hardware clocks. It can also act as an SNTP server in its own right.

.SH AUTHOR
.P
daytime and libUseful are (C) 2010 Colum Paget. They are released under the GPL so you may do anything with them that the GPL allows.
.P
Email: colums.projects@gmail.com
.br
Website: www.cjpaget.co.uk

.SH DISCLAIMER
.P
  This is free software. It comes with no guarentees and I take no responsiblity if it makes your computer explode or opens a portal to the demon dimensions, though if it does the latter I\(aqd like to be notified.

.SH USAGE
.nf
   daytime -daytime|-time|-nist|-http|-ssh|-ntp|-sntp <server> [-s] [-r] [-tz <timezone>]
   daytime <url> [-s] [-r] [-tz <timezone>]
   daytime -sntp-bcast <broadcast net> [-sntp-version <version>]
   daytime -sntpd [-sntp-stratum <stratum>] [-sntp-version <version>]
   daytime -S [date or time specifier]
.fi
.P

.SH OPTIONS
.nf
	 -daytime	Get  time from daytime (RFC-867, port 13) server
	 -time		Get  time from time (RFC-868, port 123) server
	 -nist		Get  time from NIST daytime server
	 -https		Get  time from a web server
	 -http		Get  time from a web server
	 -ssh 		Get  time from unix SSH server using the 'date' command
	 -sntp		Get  time from a SNTP server. (Not full NTP, only accurate to seconds). If server arg is \(aqbcast\(aq then wait to recieve sntp broadcast.
	 -ntp		Get  time from a SNTP server. (Not full NTP, only accurate to seconds). If server arg is \(aqbcast\(aq then wait to recieve sntp broadcast.
	 -sntp-bcast	 Broadcast  SNTP Packets to supplied address. This arg can be used multiple times to bcast to multiple nets on a multihomed host
	 -sntp-version Set NTP version. Some devices only accept version 1 in broadcast mode. 
	 -sntpd	in  Daemon mode (implies -d) and provide an SNTP service.
	 -d		Daemon  mode. Background and stay running. Needed to recieve broadcast times
	 -D		Daemon  mode WITHOUT BACKGROUNDING.
	 -P		Pidfile path for daemon mode.
	 -t		Sleep  time. Time between checks when in daemon mode, or between SNTP broadcasts (default 30 secs).
	 -s		Set clock to time we got from server (requires root permissions).
	 -S		Set clock from the command-line (requires root permissions).
	 -r		Set  hardware RTC clock
	 -v		Verbose output
	 -l		Syslog significant events
	 -tz		Timezone  of remote host
	 -servers	List  of some servers to try
	 -?		This  help
.fi
.P
If no server specified, http time from www.google.com will be tried first, then ntp from pool.ntp.org.
Servers can be specified as a host/port pair, like \(aqtime.somewhere.com:8080\(aq

.SH Command-line set date/time.

The '-S' switch allows setting a date or time from the command-line. This can be expressed in one of the following formats:

.nf
   HH:MM                -  time expressed in hours and minutes, date will stay as current.
   HH:MM:SS             -  time expressed in hours, minutes and seconds, date will stay as current.
   YYYY/mm/dd           -  date expressed in year, month, day. Time will stay as current.
   dd/mm/YYYY           -  date expressed in year, month, day. Time will stay as current.
   YYYY/mm/dd HH:MM:SS  -  date and time.
   dd/mm/YYYY HH:MM:SS  -  date and time.
   HH:MM:SS YYYY/mm/dd  -  date and time.
   HH:MM:SS dd/mm/YYYY  -  date and time.
   YYYY-mm-ddTHH:MM:SS  -  date and time.
   YYYY/mm/ddTHH:MM:SS  -  date and time.
   Sun Jan 20 15:55:37 GMT 2019   -  standard output of the 'date' command
   Sun Jan 20 15:55:37 2019       -  'date' style without zone
   Jan 20 15:55:37 GMT 2019       -  'date' style without day
   Jan 20 15:55:37 2019           -  'date' style without day and zone
.fi
.P
any character can be used as a separator in date, but time needs to use ':'
.P

.SH SNTP Broadcasts and Daemon mode.
Receiving the time as an SNTP broadcast requires having daytime stay running and wait for the message. To faciliate this a \(aqdaemon mode\(aq has been added. When -d or -D is used, daytime will stay running and do whatever it was told to do periodically. So:
	daytime -t 600 -d -sntp-bcast 192.168.1.255 -sntp-bcast 192.168.2.255
.P
Will send sntp broadcasts of the current time to the networks 192.168.1.x and 192.168.2.x. The -t flag can be used to specify a time between broadcasts.

.nf
	daytime \-s \-d \-sntp bcast
.fi
.ad b

.P
Will persist and wait to recieve sntp broadcasts and set the system time from them. NOTE -t cannot be used in sntp broadcast receive mode

.nf
	daytime \-t 3600 \-s \-http www.google.com
.fi
.ad b

.P
Will check the time with google via http every hour, and set the system time to it
.SH SNTP Server

.P
the -sntpd option will put daytime into SNTP server mode, where it will reply to SNTP requests on port 123. This can be combined with other actions, so for example:

.nf
	daytime \-sntpd \-sntp\-bcast 192.168.2.255 \-daytime time.somewhere.com \-t 60
.fi
.ad b

.P
Will run as an SNTP server, updating time using daytime protocol to \(aqtime.somewhere.com\(aq every 60 seconds and sending sntp broadcasts every 60 seconds too
.P
Thanks to Robert Crowley (http://tools.99k.org/) and Andrew Benton for bug reports
